name = "seyed-qeshmi-store"
main = "index.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "seyed-qeshmi-store"
database_id = "1ce51307-aa51-4a55-b5e5-1d81bcf3efb8"
